### ISSUE TITLE
Product search limited to page size

### ISSUE THREAD

**Issue by madchap** [DefectDojo/Burp-Plugin#25]
Hi,

I was testing the new plugin @ihebski (thanks!) and the connection works and all :+1: 

However, the product search seems to be limited to the default page size, which is 25. So for my 76 products, I am missing a good chunk of them. I am guessing the same may be true for engagements and tests.

It should return all items.

Thanks!

**Comment by ihebski** [comment]
Hello @madchap,

Thanks a lot for your review :1st_place_medal:  ! Glad to hear your feedback.

I guess we have to add a `limit` and `offset` arguments per request, since, the api do not support a pull of all available data(check documentation under [/api/v2/doc/?format=openapi](url)).

I have created a test case with 1500 dataset for products/engagements/findings, I have set the api to pull the data with the following arguments `/api/v2/products/?limit=2000&offset=0`, it seems solves the issue, we can pull 2000 records per request which I guess good enough to get all data.

I will patch the endpoints and submit a pull request .

Thanks a lot,
Regards.

**Comment by madchap** [comment]
Yes, that's probably the quick solution here.

I think you can up the limit to 5000.

**Comment by ihebski** [comment]
@madchap I have changed the limit to `4000` item per request (I was able to get all items in my lab).
The new version is available, you can test it from here https://github.com/ihebski/Burp-Plugin 

Thanks a lot.

**Comment by madchap** [comment]
Works well, thanks :)
